# Generated by Django 4.0.3 on 2022-04-01 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_first_name_customer_given_name_and_more'),
    ]

    operations = [
        migrations.RunSQL("""
                INSERT INTO mysite.store_collection (item)
                VALUES ('collection1')
            """, """
                DELETE FROM mysite.store_collection
                WHERE 'collection1'
            """)
    ]
